version: "3.8"

services:
  envoy:
    image: envoyproxy/envoy-debug-dev:latest
    ports:
      - "80:80"
      - "8800:8800"
      - "8081:8081"
    volumes:
      - ./envoy.yaml:/etc/envoy/envoy.yaml
  api:
    build:
      context: .
      dockerfile: webapp.Dockerfile
    command: ["/docker-gs-ping"]
    ports:
      - "8080:8080"
